<script type="text/javascript">
    var ajaxUrl = '<?php echo $this->getUrl('insurance/ajax/getDeliveryInsurance') ?>';
</script>
<ul class="form-list">
    <li>
        <label for="delivery-insurance"><?php echo $this->__('Delivery insurance') ?></label>
        <div class="input-box">
            <input type="checkbox" id="delivery-insurance" name="deliveryInsurance" />
            <input type="hidden" id="quote-id" name="quoteId" value="<?php echo $this->htmlEscape($this->getQuote()->getId()) ?>" />
        </div>
        <p id="place-delivery-insurance-cost"></p>
    </li>
</ul>